In [1]:
import pandas as pd
import numpy as np

In [9]:
import datetime as dt

In [11]:
dt.datetime.utcfromtimestamp(1417412423)

datetime.datetime(2014, 12, 1, 5, 40, 23)

In [ ]:
pd.datetime()

In [14]:
header = ["unixtime", "price" , "amount"]

In [15]:
kraken = pd.read_csv('./krakenUSD.csv.gz', names=header)

In [16]:
kraken = pd.read_csv('./krakenUSD.csv.gz', names=header)

           unixtime        price        amount
0        1389118697    874.67040  1.069059e-02
1        1389118703    883.32614  1.063823e-02
2        1389118711    892.06753  1.058614e-02
3        1389118871    883.23085  1.074498e-02
4        1389118879    874.48165  1.079876e-02
5        1389121655    866.10944  1.343143e-02
6        1389121664    866.10944  1.341473e-02
7        1389121670    866.10944  1.339804e-02
8        1389121679    866.10944  1.338138e-02
9        1389121957    866.09944  1.343549e-02
10       1389121964    866.09944  1.341878e-02
11       1389121973    866.09944  1.340209e-02
12       1389121979    866.09944  1.338542e-02
13       1389121996    866.09944  6.281790e-03
14       1389122006    865.81913  1.085281e-02
15       1389122016    860.00000  5.000000e-02
16       1389122180    870.00000  2.928730e-03
17       1389122199    860.00000  5.000000e-02
18       1389122207    860.00000  5.000000e-02
19       1389122213    860.00000  5.000000e-02
20       1389122219    860.00000  5.000000e-02
21       1389122228    860.00000  5.000000e-02
22       1389122233    860.00000  5.000000e-02
23       1389122263    857.24239  1.090713e-02
24       1389122268    855.00000  5.000000e-02
25       1389122306    855.00000  1.352235e-02
26       1389122315    855.00000  5.000000e-02
27       1389122320    855.00000  5.000000e-02
28       1389122327    855.00000  5.000000e-02
29       1389122335    855.00000  3.500000e-01
...             ...          ...           ...
8046960  1520291353  11590.10000  1.730000e-02
8046961  1520291374  11590.00000  2.709556e-02
8046962  1520291385  11585.80000  2.000000e-01
8046963  1520291385  11585.10000  9.275635e-02
8046964  1520291385  11585.10000  2.136500e-04
8046965  1520291423  11585.00000  2.012000e-01
8046966  1520291431  11585.00000  2.000000e+00
8046967  1520291448  11585.10000  2.400000e-01
8046968  1520291448  11585.10000  2.164844e-02
8046969  1520291448  11588.80000  1.107339e-02
8046970  1520291448  11588.80000  8.500000e-02
8046971  1520291448  11588.90000  2.453000e-01
8046972  1520291461  11585.10000  3.026900e-03
8046973  1520291486  11591.10000  2.092270e-03
8046974  1520291491  11585.00000  2.893057e-02
8046975  1520291491  11585.00000  6.926000e-05
8046976  1520291491  11585.00000  1.700000e-07
8046977  1520291506  11591.00000  5.345470e-03
8046978  1520291506  11591.00000  3.210000e-06
8046979  1520291506  11591.00000  7.800000e-02
8046980  1520291508  11585.30000  1.550000e-02
8046981  1520291557  11585.30000  7.333708e-02
8046982  1520291565  11589.90000  1.550000e-02
8046983  1520291568  11585.00000  1.300000e-02
8046984  1520291583  11585.10000  1.500000e-03
8046985  1520291591  11585.10000  7.183708e-02
8046986  1520291591  11585.10000  7.800000e-02
8046987  1520291591  11585.30000  1.501629e-01
8046988  1520291642  11585.10000  1.500000e-01
8046989  1520291667  11585.00000  1.606000e-01

[8046990 rows x 3 columns]

In [5]:
coinbase = pd.read_csv('./coinbaseUSD.csv.gz')

In [6]:
coinbase

          1417412036  300.000000000000  0.010000000000
0         1417412423            300.00        0.010000
1         1417415048            370.00        0.010000
2         1417416612            370.00        0.026556
3         1417498166            377.00        0.010000
4         1417517949            377.75        0.250000
5         1417517949            378.00        3.750000
6         1417518257            378.00        4.900000
7         1417518340            378.00        5.200000
8         1417545780            378.00        0.100000
9         1417546703            378.00        0.793600
10        1417550521            378.00        0.010000
11        1417584956            377.90        0.010000
12        1417585904            378.00        0.066084
13        1417586889            378.00        0.010524
14        1417631579            378.00        0.350000
15        1417637186            377.01        0.100000
16        1417647358            378.00        0.010000
17        1417657685            377.10        0.010000
18        1417830085            378.00        0.015000
19        1418077586            375.01        0.010000
20        1418077586            375.00        0.225000
21        1418179364            398.00        0.010000
22        1418179389            360.50        0.010000
23        1418355001            379.00        0.050000
24        1418355193            364.99        0.010000
25        1418355875            360.50        0.990000
26        1418355878            360.00        0.100000
27        1418355965            350.00        2.000000
28        1418936217            345.00        1.000000
29        1418936217            340.00        1.000000
...              ...               ...             ...
38182367  1520293936          11541.68        0.860000
38182368  1520293936          11541.68        1.000000
38182369  1520293936          11541.68        0.499923
38182370  1520293936          11541.68        0.001000
38182371  1520293936          11541.68        0.001000
38182372  1520293936          11541.68        1.000000
38182373  1520293936          11541.68        0.500000
38182374  1520293936          11541.68        0.396229
38182375  1520293936          11541.68        0.001000
38182376  1520293936          11541.68        0.250000
38182377  1520293936          11541.68        1.000000
38182378  1520293936          11541.68        0.409522
38182379  1520293943          11541.68        0.022100
38182380  1520293955          11541.67        0.836300
38182381  1520293966          11541.67        0.674827
38182382  1520293967          11541.68        0.160600
38182383  1520293967          11541.68        0.436418
38182384  1520293979          11541.68        0.032200
38182385  1520293982          11541.68        0.004321
38182386  1520293990          11541.68        0.305000
38182387  1520293992          11541.67        0.001731
38182388  1520293995          11541.67        0.002745
38182389  1520294001          11541.68        0.165300
38182390  1520294013          11541.67        0.039500
38182391  1520294018          11541.68        0.011467
38182392  1520294024          11541.67        0.100000
38182393  1520294025          11541.68        0.053900
38182394  1520294035          11541.68        0.001560
38182395  1520294037          11541.67        0.012500
38182396  1520294050          11541.67        0.021700

[38182397 rows x 3 columns]

In [7]:
coinbase.shape

(38182397, 3)

In [18]:
kraken['timestamp'] = pd.to_datetime(kraken['unixtime'],unit='s')

In [24]:
kraken.drop('unixtime', axis=1, inplace=True)

In [30]:
kraken.set_index('timestamp', inplace = True)

In [32]:
kraken.groupby(pd.TimeGrouper('5Min'))['price'].mean()

timestamp
2014-01-07 18:15:00      883.354690
2014-01-07 18:20:00      878.856250
2014-01-07 18:25:00             NaN
2014-01-07 18:30:00             NaN
2014-01-07 18:35:00             NaN
2014-01-07 18:40:00             NaN
2014-01-07 18:45:00             NaN
2014-01-07 18:50:00             NaN
2014-01-07 18:55:00             NaN
2014-01-07 19:00:00             NaN
2014-01-07 19:05:00      866.109440
2014-01-07 19:10:00      865.188047
2014-01-07 19:15:00      850.234580
2014-01-07 19:20:00      847.631533
2014-01-07 19:25:00      837.535667
2014-01-07 19:30:00      835.020020
2014-01-07 19:35:00      845.771138
2014-01-07 19:40:00      862.519282
2014-01-07 19:45:00             NaN
2014-01-07 19:50:00             NaN
2014-01-07 19:55:00      860.490700
2014-01-07 20:00:00      873.274820
2014-01-07 20:05:00             NaN
2014-01-07 20:10:00      873.284820
2014-01-07 20:15:00             NaN
2014-01-07 20:20:00             NaN
2014-01-07 20:25:00             NaN
2014-01-07 20:30:00             NaN
2014-01-07 20:35:00             NaN
2014-01-07 20:40:00      862.831560
                           ...
2018-03-05 20:45:00    11589.851579
2018-03-05 20:50:00    11580.953600
2018-03-05 20:55:00    11577.956429
2018-03-05 21:00:00    11588.948684
2018-03-05 21:05:00    11587.977778
2018-03-05 21:10:00    11556.037500
2018-03-05 21:15:00    11518.023715
2018-03-05 21:20:00    11546.734667
2018-03-05 21:25:00    11533.746835
2018-03-05 21:30:00    11539.466087
2018-03-05 21:35:00    11555.979104
2018-03-05 21:40:00    11562.130435
2018-03-05 21:45:00    11562.097826
2018-03-05 21:50:00    11552.782500
2018-03-05 21:55:00    11541.249153
2018-03-05 22:00:00    11547.422857
2018-03-05 22:05:00    11555.337209
2018-03-05 22:10:00    11561.309524
2018-03-05 22:15:00    11582.651899
2018-03-05 22:20:00    11587.371014
2018-03-05 22:25:00    11591.850000
2018-03-05 22:30:00    11592.381295
2018-03-05 22:35:00    11591.339344
2018-03-05 22:40:00    11582.102000
2018-03-05 22:45:00    11579.286047
2018-03-05 22:50:00    11561.979167
2018-03-05 22:55:00    11563.657895
2018-03-05 23:00:00    11570.416129
2018-03-05 23:05:00    11589.857447
2018-03-05 23:10:00    11586.684000
Freq: 5T, Name: price, dtype: float64

In [37]:
kraken.groupby(pd.TimeGrouper('30Min')).agg({'price':['min','max','first','last'], 'amount':['sum']})

                           price                                         \
                             min          max        first         last
timestamp
2014-01-07 18:00:00    874.48165    892.06753    874.67040    874.48165
2014-01-07 18:30:00          NaN          NaN          NaN          NaN
2014-01-07 19:00:00    830.00001    870.00000    866.10944    835.02002
2014-01-07 19:30:00    835.02002    873.23850    835.02002    864.72744
2014-01-07 20:00:00    873.27482    873.28482    873.27482    873.28482
2014-01-07 20:30:00    854.09013    871.26595    862.83156    854.09013
2014-01-07 21:00:00    830.00000    845.62959    845.62959    845.53829
2014-01-07 21:30:00    820.00000    845.25471    837.16249    845.25471
2014-01-07 22:00:00    810.00000    853.46532    828.69089    819.33223
2014-01-07 22:30:00    810.01000    843.96889    835.70868    810.01000
2014-01-07 23:00:00    810.78460    837.02349    819.14544    837.02349
2014-01-07 23:30:00    810.00000    820.62107    820.62107    810.00000
2014-01-08 00:00:00    788.00000    894.04167    810.00000    788.00000
2014-01-08 00:30:00    803.69481    819.67028    803.69481    819.67028
2014-01-08 01:00:00    795.64764    803.75817    803.75817    795.64764
2014-01-08 01:30:00    803.52134    844.06440    803.52134    844.06440
2014-01-08 02:00:00    844.06440    849.68481    844.06440    849.68481
2014-01-08 02:30:00    827.43464    835.71312    835.71312    827.43464
2014-01-08 03:00:00    827.25601    849.68481    835.62289    835.44252
2014-01-08 03:30:00    835.44252    849.68481    835.44252    849.68481
2014-01-08 04:00:00    849.67481    849.67481    849.67481    849.67481
2014-01-08 04:30:00    827.07750    835.35242    835.35242    835.26222
2014-01-08 05:00:00    826.98822    835.26222    835.26222    826.98822
2014-01-08 05:30:00    835.15209    835.15209    835.15209    835.15209
2014-01-08 06:00:00    827.00000    843.43697    835.17209    827.00000
2014-01-08 06:30:00    827.00000    830.00000    830.00000    827.00000
2014-01-08 07:00:00    810.51023    827.00000    827.00000    810.51023
2014-01-08 07:30:00    812.89612    835.00000    818.53104    812.89612
2014-01-08 08:00:00    820.94055    835.00000    820.94055    835.00000
2014-01-08 08:30:00    835.00000    899.84281    835.00000    836.76145
...                          ...          ...          ...          ...
2018-03-05 08:30:00  11422.50000  11517.30000  11517.30000  11443.70000
2018-03-05 09:00:00  11426.00000  11481.90000  11443.30000  11459.60000
2018-03-05 09:30:00  11450.00000  11489.00000  11453.90000  11462.30000
2018-03-05 10:00:00  11444.00000  11463.50000  11458.80000  11444.00000
2018-03-05 10:30:00  11428.70000  11513.60000  11444.30000  11489.00000
2018-03-05 11:00:00  11464.20000  11489.20000  11489.20000  11482.40000
2018-03-05 11:30:00  11474.60000  11532.30000  11482.30000  11502.00000
2018-03-05 12:00:00  11501.90000  11571.10000  11502.00000  11538.60000
2018-03-05 12:30:00  11493.40000  11544.60000  11535.10000  11537.70000
2018-03-05 13:00:00  11473.00000  11537.50000  11537.20000  11506.40000
2018-03-05 13:30:00  11491.90000  11518.90000  11506.40000  11514.20000
2018-03-05 14:00:00  11469.90000  11535.90000  11513.80000  11476.80000
2018-03-05 14:30:00  11449.90000  11494.20000  11477.40000  11467.10000
2018-03-05 15:00:00  11452.30000  11502.60000  11467.10000  11455.50000
2018-03-05 15:30:00  11455.30000  11507.00000  11455.50000  11490.60000
2018-03-05 16:00:00  11480.00000  11537.90000  11485.60000  11537.90000
2018-03-05 16:30:00  11505.40000  11545.80000  11528.50000  11517.80000
2018-03-05 17:00:00  11496.80000  11537.60000  11517.80000  11514.70000
2018-03-05 17:30:00  11470.40000  11515.00000  11514.70000  11471.10000
2018-03-05 18:00:00  11471.10000  11510.10000  11480.80000  11505.00000
2018-03-05 18:30:00  11505.00000  11666.40000  11505.00000  11646.40000
2018-03-05 19:00:00  11626.60000  11666.40000  11649.60000  11637.00000
2018-03-05 19:30:00  11625.30000  11645.00000  11637.00000  11627.70000
2018-03-05 20:00:00  11615.00000  11666.40000  11627.80000  11615.00000
2018-03-05 20:30:00  11546.00000  11639.30000  11611.20000  11574.60000
2018-03-05 21:00:00  11476.80000  11612.20000  11588.20000  11522.00000
2018-03-05 21:30:00  11517.70000  11576.00000  11523.80000  11543.00000
2018-03-05 22:00:00  11542.50000  11598.30000  11549.90000  11589.70000
2018-03-05 22:30:00  11557.70000  11608.90000  11589.70000  11557.70000
2018-03-05 23:00:00  11550.20000  11606.40000  11561.30000  11585.00000

                         amount
                            sum
timestamp
2014-01-07 18:00:00    0.053459
2014-01-07 18:30:00         NaN
2014-01-07 19:00:00    6.363048
2014-01-07 19:30:00    1.202370
2014-01-07 20:00:00    0.088421
2014-01-07 20:30:00    0.655238
2014-01-07 21:00:00    0.074903
2014-01-07 21:30:00    2.973933
2014-01-07 22:00:00    2.613404
2014-01-07 22:30:00    0.909697
2014-01-07 23:00:00    0.560297
2014-01-07 23:30:00    0.127610
2014-01-08 00:00:00    2.510893
2014-01-08 00:30:00    0.223226
2014-01-08 01:00:00    0.072614
2014-01-08 01:30:00    0.205299
2014-01-08 02:00:00    0.210898
2014-01-08 02:30:00    0.022178
2014-01-08 03:00:00    0.323776
2014-01-08 03:30:00    0.404132
2014-01-08 04:00:00    0.744179
2014-01-08 04:30:00    0.033142
2014-01-08 05:00:00    0.011164
2014-01-08 05:30:00    0.000151
2014-01-08 06:00:00    0.121862
2014-01-08 06:30:00    0.977761
2014-01-08 07:00:00    0.526844
2014-01-08 07:30:00    0.075928
2014-01-08 08:00:00    0.050000
2014-01-08 08:30:00    0.083013
...                         ...
2018-03-05 08:30:00  107.693350
2018-03-05 09:00:00   82.779518
2018-03-05 09:30:00  126.536005
2018-03-05 10:00:00  175.002779
2018-03-05 10:30:00   98.977701
2018-03-05 11:00:00   22.061258
2018-03-05 11:30:00   38.026491
2018-03-05 12:00:00  139.265999
2018-03-05 12:30:00   69.786087
2018-03-05 13:00:00   59.131304
2018-03-05 13:30:00   26.822804
2018-03-05 14:00:00   58.686338
2018-03-05 14:30:00  119.458916
2018-03-05 15:00:00   71.914818
2018-03-05 15:30:00   75.854024
2018-03-05 16:00:00   54.340335
2018-03-05 16:30:00   53.890290
2018-03-05 17:00:00   54.764233
2018-03-05 17:30:00  144.396582
2018-03-05 18:00:00  118.254432
2018-03-05 18:30:00  411.381795
2018-03-05 19:00:00  103.928375
2018-03-05 19:30:00   87.517098
2018-03-05 20:00:00  147.605125
2018-03-05 20:30:00  176.894683
2018-03-05 21:00:00  145.233505
2018-03-05 21:30:00   66.805073
2018-03-05 22:00:00   59.518437
2018-03-05 22:30:00   59.713860
2018-03-05 23:00:00   27.054989

[72875 rows x 5 columns]

In [34]:
kraken

                           price        amount
timestamp
2014-01-07 18:18:17    874.67040  1.069059e-02
2014-01-07 18:18:23    883.32614  1.063823e-02
2014-01-07 18:18:31    892.06753  1.058614e-02
2014-01-07 18:21:11    883.23085  1.074498e-02
2014-01-07 18:21:19    874.48165  1.079876e-02
2014-01-07 19:07:35    866.10944  1.343143e-02
2014-01-07 19:07:44    866.10944  1.341473e-02
2014-01-07 19:07:50    866.10944  1.339804e-02
2014-01-07 19:07:59    866.10944  1.338138e-02
2014-01-07 19:12:37    866.09944  1.343549e-02
2014-01-07 19:12:44    866.09944  1.341878e-02
2014-01-07 19:12:53    866.09944  1.340209e-02
2014-01-07 19:12:59    866.09944  1.338542e-02
2014-01-07 19:13:16    866.09944  6.281790e-03
2014-01-07 19:13:26    865.81913  1.085281e-02
2014-01-07 19:13:36    860.00000  5.000000e-02
2014-01-07 19:16:20    870.00000  2.928730e-03
2014-01-07 19:16:39    860.00000  5.000000e-02
2014-01-07 19:16:47    860.00000  5.000000e-02
2014-01-07 19:16:53    860.00000  5.000000e-02
2014-01-07 19:16:59    860.00000  5.000000e-02
2014-01-07 19:17:08    860.00000  5.000000e-02
2014-01-07 19:17:13    860.00000  5.000000e-02
2014-01-07 19:17:43    857.24239  1.090713e-02
2014-01-07 19:17:48    855.00000  5.000000e-02
2014-01-07 19:18:26    855.00000  1.352235e-02
2014-01-07 19:18:35    855.00000  5.000000e-02
2014-01-07 19:18:40    855.00000  5.000000e-02
2014-01-07 19:18:47    855.00000  5.000000e-02
2014-01-07 19:18:55    855.00000  3.500000e-01
...                          ...           ...
2018-03-05 23:09:13  11590.10000  1.730000e-02
2018-03-05 23:09:34  11590.00000  2.709556e-02
2018-03-05 23:09:45  11585.80000  2.000000e-01
2018-03-05 23:09:45  11585.10000  9.275635e-02
2018-03-05 23:09:45  11585.10000  2.136500e-04
2018-03-05 23:10:23  11585.00000  2.012000e-01
2018-03-05 23:10:31  11585.00000  2.000000e+00
2018-03-05 23:10:48  11585.10000  2.400000e-01
2018-03-05 23:10:48  11585.10000  2.164844e-02
2018-03-05 23:10:48  11588.80000  1.107339e-02
2018-03-05 23:10:48  11588.80000  8.500000e-02
2018-03-05 23:10:48  11588.90000  2.453000e-01
2018-03-05 23:11:01  11585.10000  3.026900e-03
2018-03-05 23:11:26  11591.10000  2.092270e-03
2018-03-05 23:11:31  11585.00000  2.893057e-02
2018-03-05 23:11:31  11585.00000  6.926000e-05
2018-03-05 23:11:31  11585.00000  1.700000e-07
2018-03-05 23:11:46  11591.00000  5.345470e-03
2018-03-05 23:11:46  11591.00000  3.210000e-06
2018-03-05 23:11:46  11591.00000  7.800000e-02
2018-03-05 23:11:48  11585.30000  1.550000e-02
2018-03-05 23:12:37  11585.30000  7.333708e-02
2018-03-05 23:12:45  11589.90000  1.550000e-02
2018-03-05 23:12:48  11585.00000  1.300000e-02
2018-03-05 23:13:03  11585.10000  1.500000e-03
2018-03-05 23:13:11  11585.10000  7.183708e-02
2018-03-05 23:13:11  11585.10000  7.800000e-02
2018-03-05 23:13:11  11585.30000  1.501629e-01
2018-03-05 23:14:02  11585.10000  1.500000e-01
2018-03-05 23:14:27  11585.00000  1.606000e-01

[8046990 rows x 2 columns]

In [39]:
from pandas_datareader import data, wb

In [40]:
data.GoogleDailyReader?

In [44]:
spy = data.GoogleDailyReader(symbols = 'SPY', start = '1/1/2017')

In [50]:
test_df = spy.read()

In [51]:
test_df

              Open    High     Low   Close     Volume
Date
2017-01-03  225.04  225.83  223.88  225.24   91366522
2017-01-04  225.62  226.75  225.61  226.58   78744433
2017-01-05  226.27  226.58  225.48  226.40   78379012
2017-01-06  226.53  227.75  225.90  227.21   71559922
2017-01-09  226.91  227.07  226.42  226.46   46939676
2017-01-10  226.48  227.45  226.01  226.46   63771939
2017-01-11  226.36  227.10  225.59  227.10   74650016
2017-01-12  226.50  226.75  224.96  226.53   72113181
2017-01-13  226.73  227.40  226.69  227.05   62717865
2017-01-17  226.31  226.78  225.80  226.25   61240814
2017-01-18  226.54  226.80  225.90  226.75   54793302
2017-01-19  226.84  227.00  225.41  225.91   66608787
2017-01-20  226.70  227.31  225.97  226.74  129168623
2017-01-23  226.35  226.80  225.27  226.15   75061645
2017-01-24  226.40  228.08  226.27  227.60   95555295
2017-01-25  228.70  229.57  228.51  229.57   84437712
2017-01-26  229.40  229.71  229.01  229.33   59970719
2017-01-27  229.42  229.59  228.76  228.97   59711118
2017-01-30  228.17  228.20  226.41  227.55   79737252
2017-01-31  226.98  227.60  226.32  227.53   75880805
2017-02-01  228.26  228.59  226.94  227.62   79117651
2017-02-02  227.20  228.10  226.82  227.77   69657560
2017-02-03  228.82  229.55  228.46  229.34   80563168
2017-02-06  228.87  229.33  228.54  228.93   57790108
2017-02-07  229.38  229.66  228.72  228.94   57931151
2017-02-08  228.61  229.39  228.31  229.24   51566218
2017-02-09  229.56  230.95  229.52  230.60   65955245
2017-02-10  231.00  231.77  230.62  231.51   66015892
2017-02-13  232.08  233.07  232.05  232.77   55182050
2017-02-14  232.56  233.71  232.16  233.70   71108983
...            ...     ...     ...     ...        ...
2018-01-22  280.17  282.69  280.11  282.69   91322408
2018-01-23  282.74  283.62  282.37  283.29   97084700
2018-01-24  284.02  284.70  281.84  283.18  134816117
2018-01-25  284.16  284.27  282.40  283.30   84587313
2018-01-26  284.25  286.63  283.96  286.58  107743119
2018-01-29  285.93  286.43  284.50  284.68   90118337
2018-01-30  282.60  284.74  281.22  281.76  131796419
2018-01-31  282.73  283.30  280.68  281.90  118948131
2018-02-01  281.07  283.06  280.68  281.58   90102470
2018-02-02  280.08  280.23  275.41  275.45  173174790
2018-02-05  273.45  275.85  263.31  263.93  294681816
2018-02-06  259.94  269.70  258.70  269.13  355026782
2018-02-07  268.50  272.36  267.58  267.67  167376100
2018-02-08  268.01  268.17  257.59  257.63  246449505
2018-02-09  260.80  263.61  252.92  261.50  283565315
2018-02-12  263.83  267.01  261.66  265.34  143735976
2018-02-13  263.97  266.62  263.31  266.00   81223640
2018-02-14  264.31  270.00  264.30  269.59  120735685
2018-02-15  271.57  273.04  268.77  273.03  111200286
2018-02-16  272.32  275.32  272.27  273.11  160420135
2018-02-20  272.03  273.67  270.50  271.40   86369662
2018-02-21  271.90  274.72  269.94  270.05   98883740
2018-02-22  271.10  273.05  269.64  270.40  110511290
2018-02-23  271.79  274.71  271.25  274.71   92766428
2018-02-26  275.93  278.01  275.26  277.90   86491406
2018-02-27  278.11  278.92  274.36  274.43   99099165
2018-02-28  275.68  276.19  271.29  271.65  121907767
2018-03-01  271.41  273.17  266.00  267.70  176855077
2018-03-02  265.80  269.72  264.82  269.08  139083217
2018-03-05  267.73  272.89  267.61  272.19   97307387

[294 rows x 5 columns]